=== StelianaDimitrova/XML-Hotel/hotel.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT hotel (room+, hall*, restaurant*)>

    <!ELEMENT room (number, price, cleaning_service?, reservation)>
        <!ELEMENT number (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT cleaning_service (number_of_maids, cleaning_duration, number_of_cleanings_per_stay)>
            <!ELEMENT number_of_maids (#PCDATA)>
            <!ELEMENT cleaning_duration (#PCDATA)>
            <!ELEMENT number_of_cleanings_per_stay (#PCDATA)>
        <!ELEMENT reservation (guest_name, phone_number, check_in_date, check_out_date)>
            <!ELEMENT guest_name (#PCDATA)>
            <!ELEMENT phone_number (#PCDATA)>
            <!ELEMENT check_in_date (#PCDATA)>
            <!ELEMENT check_out_date (#PCDATA)>

    <!ELEMENT hall (name, note?, work_time, capacity, activity*)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT note (#PCDATA)>
        <!ELEMENT work_time (#PCDATA)>
        <!ELEMENT capacity (#PCDATA)>
        <!ELEMENT activity (host+, number_of_people, age_restrictions, duration, number_of_breaks)>
            <!ELEMENT host (#PCDATA)>
            <!ELEMENT number_of_people (#PCDATA)>
            <!ELEMENT age_restrictions (#PCDATA)>
            <!ELEMENT duration (#PCDATA)>
            <!ELEMENT number_of_breaks (#PCDATA)>
            
    <!ELEMENT restaurant (menu, seating_capacity, opening_hours)>
        <!ELEMENT menu (dish+)>
            <!ELEMENT dish (category, food_name, description, price_of_dish, amount)>
                <!ELEMENT category (#PCDATA)>
                <!ELEMENT food_name (#PCDATA)>
                <!ELEMENT description (#PCDATA)>
                <!ELEMENT price_of_dish (#PCDATA)>
                <!ELEMENT amount (#PCDATA)>
        <!ELEMENT seating_capacity (#PCDATA)>
        <!ELEMENT opening_hours (#PCDATA)>


<!ATTLIST hotel star_rating CDATA #REQUIRED>

<!ATTLIST room id ID #REQUIRED>
<!ATTLIST room type (Единична|Двойна|Двойка|Тройна|Четворна|Студио|Апартамент|Кабана) "Двойна">
<!ATTLIST room view (Да|Не) "Не">
<!ATTLIST room has_tv (Да|Не) "Да">

<!ATTLIST price currency CDATA #REQUIRED>

<!ATTLIST reservation code CDATA #REQUIRED>

<!ATTLIST hall id ID #REQUIRED>
<!ATTLIST hall type (Конферентна|Бална|Спа|Фитнес|Игрална) "Конферентна">
<!ATTLIST hall fee (Безплатна|Платена) "Безплатна">
<!ATTLIST hall is_available (Да|Не) "Да">

<!ATTLIST activity type CDATA #REQUIRED>

<!ATTLIST restaurant id ID #REQUIRED>
<!ATTLIST restaurant smoking_allowed (Да|Не) "Не">
<!ATTLIST price_of_dish currency CDATA #REQUIRED>

=== StelianaDimitrova/XML-Hotel/valid_xml_3.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hotel SYSTEM "hotel.dtd">

<hotel star_rating="5">

    <room id="r304" type="Двойна" view="Да" has_tv="Да">
        <number>304</number>
        <price currency="USD">150.00</price>
        <cleaning_service>
            <number_of_maids>2</number_of_maids>
            <cleaning_duration>2 часа</cleaning_duration>
            <number_of_cleanings_per_stay>3</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res304">
            <guest_name>Иван Иванов</guest_name>
            <phone_number>089-456-7890</phone_number>
            <check_in_date>2023-01-01</check_in_date>
            <check_out_date>2023-01-05</check_out_date>
        </reservation>
    </room>

    <hall id="h7" type="Конферентна" fee="Платена" is_available="Да">
        <name>SAP зала</name>
        <work_time>9:00 ч. - 17:00 ч.</work_time>
        <capacity>100</capacity>
        <activity type="Конференция">
            <host>DICOM</host>
            <number_of_people>80</number_of_people>
            <age_restrictions>18+</age_restrictions>
            <duration>4 часа</duration>
            <number_of_breaks>2</number_of_breaks>
        </activity>
    </hall>

    <restaurant id="rest5" smoking_allowed="Не">
        <menu>
            <dish>
                <category>Предястие</category>
                <food_name>Брускета</food_name>
                <description>Препечен хляб с домати и босилек</description>
                <price_of_dish currency="EUR">8.99</price_of_dish>
                <amount>3</amount>
            </dish>
            <dish>
                <category>Основно ястие</category>
                <food_name>Сьомга на скара</food_name>
                <description>Свежо филе от сьомга на скара поднесена с гарнитура по избор</description>
                <price_of_dish currency="EUR">19.99</price_of_dish>
                <amount>1</amount>
            </dish>
        </menu>
        <seating_capacity>50</seating_capacity>
        <opening_hours>18:00 ч. - 22:00 ч.</opening_hours>
    </restaurant>

</hotel>

=== StelianaDimitrova/XML-Hotel/valid_xml.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hotel SYSTEM "hotel.dtd">

<hotel star_rating="5">

    <room id="r101" type="Двойна" view="Да" has_tv="Да">
        <number>101</number>
        <price currency="BGN">120</price>
        <cleaning_service>
            <number_of_maids>2</number_of_maids>
            <cleaning_duration>30</cleaning_duration>
            <number_of_cleanings_per_stay>3</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res101">
            <guest_name>Иван Иванов</guest_name>
            <phone_number>+359 88 1234567</phone_number>
            <check_in_date>2023-12-01</check_in_date>
            <check_out_date>2023-12-05</check_out_date>
        </reservation>
    </room>

    <room id="r102" type="Единична" view="Не" has_tv="Да">
        <number>102</number>
        <price currency="BGN">80</price>
        <reservation code="res102">
            <guest_name>Петър Петров</guest_name>
            <phone_number>+359 88 7654321</phone_number>
            <check_in_date>2023-12-01</check_in_date>
            <check_out_date>2023-12-03</check_out_date>
        </reservation>
    </room>

    <hall id="h1" type="Конферентна" fee="Платена" is_available="Не">
        <name>Зала 1</name>
        <work_time>09:00 - 18:00</work_time>
        <capacity>50</capacity>
        <activity type="Семинар">
            <host>Д-р Георги Георгиев</host>
            <number_of_people>30</number_of_people>
            <age_restrictions>Няма</age_restrictions>
            <duration>2 часа</duration>
            <number_of_breaks>1</number_of_breaks>
        </activity>
    </hall>

    <hall id="h2" type="Бална" fee="Безплатна" is_available="Не">
        <name>Зала 2</name>
        <work_time>18:00 - 06:00</work_time>
        <capacity>100</capacity>
        <activity type="Бал">
            <host>Мария Маринова</host>
            <number_of_people>80</number_of_people>
            <age_restrictions>Над 18 години</age_restrictions>
            <duration>8 часа</duration>
            <number_of_breaks>0</number_of_breaks>
        </activity>
    </hall>

    <restaurant id="rest1" smoking_allowed="Не">
        <menu>
            <dish>
                <category>Основни ястия</category>
                <food_name>Пилешки кюфтета</food_name>
                <description>Поднесени със зеленчуков гарнир</description>
                <price_of_dish currency="BGN">15</price_of_dish>
                <amount>200гр</amount>
            </dish>

            <dish>
                <category>Десерти</category>
                <food_name>Тирамису</food_name>
                <description>Италиански десерт с маскарпоне и еспресо</description>
                <price_of_dish currency="BGN">8</price_of_dish>
                <amount>150гр</amount>
            </dish>

            <dish>
                <category>Салати</category>
                <food_name>Шопска салата</food_name>
                <description>Традиционна българска салата с домати, краставици, лук, чушки и сирене</description>
                <price_of_dish currency="BGN">6</price_of_dish>
                <amount>250гр</amount>
            </dish>
        </menu>
        <seating_capacity>80</seating_capacity>
        <opening_hours>08:00 - 23:00</opening_hours>
    </restaurant>

</hotel>

=== StelianaDimitrova/XML-Hotel/valid_xml_2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hotel SYSTEM "hotel.dtd">

<hotel star_rating="3">

    <room id="r301" type="Единична" view="Да" has_tv="Не">
        <number>301</number>
        <price currency="USD">50</price>
        <cleaning_service>
            <number_of_maids>1</number_of_maids>
            <cleaning_duration>20</cleaning_duration>
            <number_of_cleanings_per_stay>2</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res301">
            <guest_name>Анна Смирнова</guest_name>
            <phone_number>089-654-3210</phone_number>
            <check_in_date>2023-10-15</check_in_date>
            <check_out_date>2023-10-20</check_out_date>
        </reservation>
    </room>

    <room id="r302" type="Двойна" view="Да" has_tv="Не">
        <number>302</number>
        <price currency="USD">120</price>
        <reservation code="res302">
            <guest_name>Джон Смит</guest_name>
            <phone_number>+359 88 456 7890</phone_number>
            <check_in_date>2023-10-18</check_in_date>
            <check_out_date>2023-10-25</check_out_date>
        </reservation>
    </room>

    <room id="r303" type="Студио" view="Да" has_tv="Да">
        <number>303</number>
        <price currency="EUR">150</price>
        <cleaning_service>
            <number_of_maids>2</number_of_maids>
            <cleaning_duration>25</cleaning_duration>
            <number_of_cleanings_per_stay>3</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res303">
            <guest_name>Петя Иванова</guest_name>
            <phone_number>+359 88 3334445</phone_number>
            <check_in_date>2023-11-01</check_in_date>
            <check_out_date>2023-11-07</check_out_date>
        </reservation>
    </room>

    <hall id="h5" type="Спа" fee="Платена" is_available="Да">
        <name>СПА Център</name>
        <note>Момент за релаксация!</note>
        <work_time>10:00 ч. - 20:00 ч.</work_time>
        <capacity>15</capacity>
        <activity type="Йога клас">
            <host>Андрей Сидерский</host>
            <number_of_people>10</number_of_people>
            <age_restrictions>16+</age_restrictions>
            <duration>1.5 часа</duration>
            <number_of_breaks>1</number_of_breaks>
        </activity>
    </hall>

    <hall id="h6" type="Игрална" fee="Безплатна" is_available="Да">
        <name>Зона за деца</name>
        <note>Забавление и игри за малките</note>
        <work_time>9:00 ч. - 18:00 ч.</work_time>
        <capacity>30</capacity>
        <activity type="Майсторска работилница">
            <host>Мая Денева</host>
            <number_of_people>20</number_of_people>
            <age_restrictions>4-12 години</age_restrictions>
            <duration>2 часа</duration>
            <number_of_breaks>1</number_of_breaks>
        </activity>
    </hall>

    <restaurant id="rest3" smoking_allowed="Не">
        <menu>
            <dish>
                <category>Предястия</category>
                <food_name>Капрезе салата</food_name>
                <description>Свежи домати, моцарела и босилек, поливани с балсамов оцет</description>
                <price_of_dish currency="EUR">5</price_of_dish>
                <amount>150гр</amount>
            </dish>

            <dish>
                <category>Основни ястия</category>
                <food_name>Печено пиле с розмарин</food_name>
                <description>Сочно печено пиле, подправено с розмарин</description>
                <price_of_dish currency="EUR">8</price_of_dish>
                <amount>200гр</amount>
            </dish>

            <dish>
                <category>Десерти</category>
                <food_name>Шоколадово фондю</food_name>
                <description>Богато шоколадово фондю, сервирано със свежи плодове и маршмелоус</description>
                <price_of_dish currency="EUR">4</price_of_dish>
                <amount>250гр</amount>
            </dish>
        </menu>
        <seating_capacity>40</seating_capacity>
        <opening_hours>10:00 ч. - 22:00 ч.</opening_hours>
    </restaurant>

</hotel>

=== StelianaDimitrova/XML-Hotel/valid_xml_5.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hotel SYSTEM "hotel.dtd">

<hotel star_rating="2">

    <room id="room500" type="Двойна" view="Да" has_tv="Да">
        <number>500</number>
        <price currency="USD">300.00</price>
        <cleaning_service>
            <number_of_maids>3</number_of_maids>
            <cleaning_duration>2 часа</cleaning_duration>
            <number_of_cleanings_per_stay>2</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res500">
            <guest_name>Десислава Чолакова</guest_name>
            <phone_number>088-789-0123</phone_number>
            <check_in_date>2024-02-01</check_in_date>
            <check_out_date>2024-02-07</check_out_date>
        </reservation>
    </room>

    <room id="room501" type="Двойна" view="Не" has_tv="Да">
        <number>501</number>
        <price currency="USD">250.00</price>
        <cleaning_service>
            <number_of_maids>2</number_of_maids>
            <cleaning_duration>1 часа</cleaning_duration>
            <number_of_cleanings_per_stay>2</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res501">
            <guest_name>Ивана Колева</guest_name>
            <phone_number>088-012-3456</phone_number>
            <check_in_date>2023-03-15</check_in_date>
            <check_out_date>2023-03-20</check_out_date>
        </reservation>
    </room>

</hotel>

=== StelianaDimitrova/XML-Hotel/valid_xml_4.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hotel SYSTEM "hotel.dtd">

<hotel star_rating="6">

    <room id="r400" type="Двойна" view="Да" has_tv="Да">
        <number>400</number>
        <price currency="USD">300.00</price>
        <cleaning_service>
            <number_of_maids>3</number_of_maids>
            <cleaning_duration>3 часа</cleaning_duration>
            <number_of_cleanings_per_stay>2</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res400">
            <guest_name>Петър Петров</guest_name>
            <phone_number>088-789-0123</phone_number>
            <check_in_date>2023-02-01</check_in_date>
            <check_out_date>2023-02-07</check_out_date>
        </reservation>
    </room>

    <room id="r401" type="Кабана" view="Да" has_tv="Да">
        <number>401</number>
        <price currency="USD">500.00</price>
        <cleaning_service>
            <number_of_maids>4</number_of_maids>
            <cleaning_duration>4 часа</cleaning_duration>
            <number_of_cleanings_per_stay>3</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res401">
            <guest_name>Елина Генчева</guest_name>
            <phone_number>088-012-3456</phone_number>
            <check_in_date>2024-03-15</check_in_date>
            <check_out_date>2024-03-20</check_out_date>
        </reservation>
    </room>

    <hall id="hall1" type="Конферентна" fee="Платена" is_available="Да">
        <name>Голяма конферентна зала</name>
        <work_time>9:00 ч. - 18:00 ч.</work_time>
        <capacity>300</capacity>
        <activity type="Конференция">
            <host>Елимекс</host>
            <number_of_people>200</number_of_people>
            <age_restrictions>Няма</age_restrictions>
            <duration>8 часа</duration>
            <number_of_breaks>3</number_of_breaks>
        </activity>
    </hall>

    <hall id="hall2" type="Бална" fee="Платена" is_available="Да">
        <name>Голяма бална зала</name>
        <work_time>20:00 ч. - 6:00 ч.</work_time>
        <capacity>150</capacity>
        <activity type="Сватба">
            <host>Мирослав Димитров</host>
            <number_of_people>100</number_of_people>
            <age_restrictions>Няма</age_restrictions>
            <duration>6 часа</duration>
            <number_of_breaks>0</number_of_breaks>
        </activity>
    </hall>

    <restaurant id="rest6" smoking_allowed="Не">
        <menu>
            <dish>
                <category>Предястие</category>
                <food_name>Сьомга на джаджан</food_name>
                <description>Сьомга с джаджан, поднесена с лимонов сос</description>
                <price_of_dish currency="EUR">15.99</price_of_dish>
                <amount>1</amount>
            </dish>
            <dish>
                <category>Основно ястие</category>
                <food_name>Стек с маслинов сос</food_name>
                <description>Стек с маслинов сос и печени картофи</description>
                <price_of_dish currency="EUR">29.99</price_of_dish>
                <amount>1</amount>
            </dish>
        </menu>
        <seating_capacity>80</seating_capacity>
        <opening_hours>18:00 ч. - 23:00 ч.</opening_hours>
    </restaurant>

    <restaurant id="rest7" smoking_allowed="Да">
        <menu>
            <dish>
                <category>Предястие</category>
                <food_name>Фурми</food_name>
                <description>Фурми с козе сирене увити в бекон</description>
                <price_of_dish currency="EUR">9.99</price_of_dish>
                <amount>1</amount>
            </dish>
            <dish>
                <category>Основно ястие</category>
                <food_name>Английски бифтек</food_name>
                <description>Английски бифтек с розмаринов сос и печени зеленчуци</description>
                <price_of_dish currency="EUR">25.99</price_of_dish>
                <amount>1</amount>
            </dish>
        </menu>
        <seating_capacity>60</seating_capacity>
        <opening_hours>19:00 ч. - 00:00 ч.</opening_hours>
    </restaurant>

</hotel>

=== StelianaDimitrova/XML-Hotel/valid_xml_1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hotel SYSTEM "hotel.dtd">

<hotel star_rating="4">

    <room id="r201" type="Студио" view="Да" has_tv="Да">
        <number>201</number>
        <price currency="EUR">180</price>
        <cleaning_service>
            <number_of_maids>3</number_of_maids>
            <cleaning_duration>45 Минути</cleaning_duration>
            <number_of_cleanings_per_stay>2</number_of_cleanings_per_stay>
        </cleaning_service>
        <reservation code="res201">
            <guest_name>Мария Иванова</guest_name>
            <phone_number>+359 88 9876543</phone_number>
            <check_in_date>2023-11-15</check_in_date>
            <check_out_date>2023-11-20</check_out_date>
        </reservation>
    </room>

    <room id="r202" type="Апартамент" view="Не" has_tv="Да">
        <number>202</number>
        <price currency="EUR">250</price>
        <reservation code="res202">
            <guest_name>Георги Петров</guest_name>
            <phone_number>+359 88 1112233</phone_number>
            <check_in_date>2023-11-18</check_in_date>
            <check_out_date>2023-11-25</check_out_date>
        </reservation>
    </room>

    <hall id="h3" type="Спа" fee="Платена" is_available="Да">
        <name>СПА Зона</name>
        <note>Пълен релакс и зареждане</note>
        <work_time>10:00 - 20:00</work_time>
        <capacity>20</capacity>
        <activity type="Масаж">
            <host>Петър Георгиев</host>
            <number_of_people>1</number_of_people>
            <age_restrictions>Няма</age_restrictions>
            <duration>1 час</duration>
            <number_of_breaks>0</number_of_breaks>
        </activity>
    </hall>

    <hall id="h4" type="Фитнес" fee="Безплатна" is_available="Да">
        <name>Фитнес Зала</name>
        <note>Тренирай здраво!</note>
        <work_time>08:00 - 22:00</work_time>
        <capacity>30</capacity>
        <activity type="Тренировка">
            <host>Димитър Йорданов</host>
            <number_of_people>10</number_of_people>
            <age_restrictions>Над 16 години</age_restrictions>
            <duration>2 часа</duration>
            <number_of_breaks>1</number_of_breaks>
        </activity>
    </hall>

    <restaurant id="rest2" smoking_allowed="Да">
        <menu>
            <dish>
                <category>Супи</category>
                <food_name>Таратор</food_name>
                <description>Кисело мляко, краставици, копър, орехи</description>
                <price_of_dish currency="BGN">3</price_of_dish>
                <amount>300гр</amount>
            </dish>

            <dish>
                <category>Основни ястия</category>
                <food_name>Паста Болонезе</food_name>
                <description>Спагети, доматен сос, сос Болонезе (кайма, лук, моркови), кашкавал</description>
                <price_of_dish currency="BGN">12</price_of_dish>
                <amount>250гр</amount>
            </dish>

            <dish>
                <category>Десерти</category>
                <food_name>Шоколадов мус</food_name>
                <description>Пухкав крем с натурален белгийски шоколад</description>
                <price_of_dish currency="BGN">8</price_of_dish>
                <amount>200гр</amount>
            </dish>
        </menu>
        <seating_capacity>60</seating_capacity>
        <opening_hours>7:00 - 00:00</opening_hours>
    </restaurant>

</hotel>
